### ISSUE TITLE
Spycheck on Windows 7 x64 strange results

### ISSUE THREAD

**Issue by ghost** [BjornRuytenberg/spycheck-linux#2]
It says that I do not have TB ports.

I have installed driver and enabled power state.

But it still says I do not have port even if now I can see it in TB tool.

![image](https://user-images.githubusercontent.com/4306334/81622345-6c387300-93f9-11ea-94f8-f12d14fce0a5.png)

**Comment by BjornRuytenberg** [comment]
This screen appears if you tell Spycheck you do not have any Thunderbolt ports. Please select the first option ("USB-C or Mini-DisplayPort with lightning symbol") and try again.
